# Generated by Django 3.2.1 on 2023-12-20 21:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryItem',
            new_name='Candidates',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Positions',
        ),
    ]
